version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: sinistro_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  # TODO: Adicionar Kestra service para orquestração real
